### ISSUE TITLE
Low hanging performance fruit?

### ISSUE THREAD

**Issue by RatanRSur** [r00tman/corrupter#6]
Hey!

Love the program!

It takes quite a while on my 4k screen however (~3s). I was wondering if there are performance improvements you're aware of that have yet to be implemented or is this about the fastest it will be in go?

**Comment by r00tman** [comment]
Thank you!

Apparently, after disabling png compression, time went down from 3.6s to 1.6s (2.25x) on 3000x2000 images. That's the easiest improvement there was.

Next, it still took 0.4s to encode an image. If the image is not NRGBA, Encoder uses .At function, which spends 0.16s in total on useless mallocs. I was using RGBA images. Now I use NRGBA images, and encoding takes 0.04s.

Current time distribution: 0.4s on decoding, 0.6s on random number generation, 0.2s on actual work. RNG is pretty much ok in golang. At least, since everything in 'math' is 64-bit, I couldn't get better times by implementing smth. like Box-Muller generator.  Decoding probably can't be much faster, because there's all this compression and Huffman coding stuff.

So, I think, optimizing from 3.6s to 1.2s (3x) is a very nice improvement.
